name: Release
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
jobs:
  release:
    runs-on: 'ubuntu-latest'

    steps:

    # Setup
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # Check Versions
    - name: Check If Versions Match
      run: |
        cargo_version=$(cargo pkgid | cut -d'#' -f 2)

        set -x
        test "${cargo_version}"   = "${GITHUB_REF_NAME#v}"

    - uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: '${{ runner.os }}-cargo-index-${{ hashFiles(''**/Cargo.lock'') }}'
    - uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: |
          --root . --path .

    # Upload Docker Image
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          withlazers/neatkube
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: withlazers
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .

    - uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        draft: true
        files: |
          bin/nk
